---
# Refer to docs/javascript/README.md for detail
extends:
  - daojs

env:
  jest: true

rules:
  lodash/prefer-lodash-method:
  - off
  - devDependencies:
    - "**/*.test.js"
  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - "**/*.demo.js"
